# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Devesh Sarda
title: Incoming UW CS DA Student 
email: devess@uw.edu
website: https://sarda-devesh.github.io/ 

# Social links
github_username:  sarda-devesh
linkedin_username: devesh-sarda-172aa9175

# About Section
# about_title: About Me
about_profile_image: images/cover_photo_devesh.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Devesh and I am incoming University of Washington student planning to study computer science. I have gotten experience in CS through robotics, internships and participating in research.
  Here is a quick summary of the information on this link: > [**Resume**](https://1drv.ms/b/s!Arx8ctObhbGoj8UJHvRroQTN-1MXWw) 

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
